### PR TITLE
Fix flaky test

### LINKED ISSUE #2458: Flaky tests in inferred-spans
During the last contrib release, there were a few flaky tests that cause some problems.

https://develocity.opentelemetry.io/s/kzarodjoam5t6/tests/task/:inferred-spans:test/details/io.opentelemetry.contrib.inferredspans.InferredSpansTest/testSetProfilerInterval()?top-execution=1

Image

Same basic thing with the [SamplingProfilerTest](https://develocity.opentelemetry.io/s/kzarodjoam5t6/tests/task/:inferred-spans:test/details/io.opentelemetry.contrib.inferredspans.internal.SamplingProfilerTest).

Seems like maybe the profiler isn't being reset correctly between tests or there is some other unexpected test interaction.

### PR DESCRIPTION
**Pull request by jackshirazi**
closes #2458

### CODE REVIEW

File: inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfiler.java [hunk 1]
```diff
@@ -394,9 +396,14 @@ public void run() {
...
-      long delay = config.getProfilingInterval().toMillis() - profilingDuration.toMillis();
-      profilingTask = scheduler.schedule(this, delay, TimeUnit.MILLISECONDS);
+    profilerLock.lock();
+    try {
+      if (!isInterrupted && !scheduler.isShutdown()) {
+        long delay = config.getProfilingInterval().toMillis() - profilingDuration.toMillis();
+        profilingTask = scheduler.schedule(this, delay, TimeUnit.MILLISECONDS);
+      }
+    } finally {
+      profilerLock.unlock();
```
Comment (jackshirazi) [inline inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfiler.java:417]: for reviewer, same code block, just pushed into try-finally block to use a lock. This ensures that setProfilerInterval is correct. The race is that run() finishes a profiling session and prepares to schedule the next one. It reads the old interval (e.g., 10s). Concurrently, the test calls setProfilerInterval (e.g., 100ms) and then reschedule(). reschedule() tries to cancel the current task. If they race, run() might successfully schedule the next task with the old 10s delay, effectively ignoring the update. The test then waits for the next session (expecting it in 100ms), but it doesn't happen for 10s, causing a timeout.

it's actually possible for an interruption to occur just before the lock was acquired. This should is handled by re-reading Thread.currentThread().isInterrupted()  to ensure no task is scheduled if an interruption occurred just before acquiring the lock

File: inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfiler.java [hunk 2]
```diff
@@ -394,9 +396,14 @@ public void run() {
         config.isNonStopProfiling() && !interrupted && postProcessingEnabled;
     setProfilingSessionOngoing(continueProfilingSession);
 
-    if (!interrupted && !scheduler.isShutdown()) {
-      long delay = config.getProfilingInterval().toMillis() - profilingDuration.toMillis();
-      profilingTask = scheduler.schedule(this, delay, TimeUnit.MILLISECONDS);
+    profilerLock.lock();
+    try {
+      if (!isInterrupted && !scheduler.isShutdown()) {
```
Comment (jackshirazi) [inline inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfiler.java]: See below comment on whether to make this change
```suggestion
      if (!Thread.currentThread().isInterrupted() && !scheduler.isShutdown()) {
```

File: inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfiler.java [hunk 3]
```diff
@@ -739,13 +746,18 @@ public void start() {
...
+      Future<?> future = this.profilingTask;
+      if (future != null) {
+        if (future.cancel(true)) {
+          Duration profilingDuration = config.getProfilingDuration();
+          long delay = config.getProfilingInterval().toMillis() - profilingDuration.toMillis();
+          profilingTask = scheduler.schedule(this, delay, TimeUnit.MILLISECONDS);
+        }
       }
+    } finally {
+      profilerLock.unlock();
```
Comment (jackshirazi) [inline inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfiler.java:789]: for reviewer, same code block just wrapped in the lock try-finally

File: inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfiler.java [hunk 4]
```diff
@@ -406,25 +413,25 @@ private void profile(Duration profilingDuration) throws Exception {
...
+        profilingSessions++;
+
+        // When post-processing is disabled activation events are ignored, but we still need to
+        // invoke this method as it is the one enforcing the sampling session duration. As a side
+        // effect it will also consume residual activation events if post-processing is disabled
+        // dynamically
+        consumeActivationEventsFromRingBufferAndWriteToFile(profilingDuration);
+      } finally {
+        String stopMessage = profiler.execute("stop");
+        logger.fine(stopMessage);
```
Comment (jackshirazi) [inline inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfiler.java:458]: for reviewer. same code block, but restructured to ensure that `profiler.execute("stop");` is definitely called as an earlier interrupt will go straight to the catch block (below) bypassing the stop - this is most likely the test flakiness ("Profiler already started") - the profiler not correctly stopped

File: inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfiler.java [hunk 5]
```diff
@@ -394,9 +396,14 @@ public void run() {
         config.isNonStopProfiling() && !interrupted && postProcessingEnabled;
```
Comment (SylvainJuge) [inline inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfiler.java:404]: Maybe we could inline `interrupted` variable and add a comment why we need the double call to `Thread.currentThread().isInterrupted()` to get an up-to-date status without using the value from the previous call.

**Review by SylvainJuge — APPROVED** [review]

File: inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfiler.java (hunk 4 above)
Comment (laurit) [reply inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfiler.java:458]: you could add a comment that explains that this is in a finally block because the preceding code be interrupted

File: inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfiler.java [hunk 6]
```diff
@@ -739,13 +746,18 @@ public void start() {
...
-    if (future != null) {
-      if (future.cancel(true)) {
-        Duration profilingDuration = config.getProfilingDuration();
-        long delay = config.getProfilingInterval().toMillis() - profilingDuration.toMillis();
-        profilingTask = scheduler.schedule(this, delay, TimeUnit.MILLISECONDS);
+    profilerLock.lock();
+    try {
+      Future<?> future = this.profilingTask;
+      if (future != null) {
+        if (future.cancel(true)) {
```
Comment (laurit) [inline inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfiler.java]: could be merged

Comment (jackshirazi) [reply inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfiler.java]: done

File: inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfiler.java (hunk 5 above)
Comment (jackshirazi) [reply inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfiler.java:404]: done

File: inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfiler.java (hunk 4 above)
Comment (jackshirazi) [reply inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfiler.java:458]: done

**Comment by trask** [comment]
@jackshirazi does the CI failure on this PR look like same or different issue than you were trying to fix here? https://scans.gradle.com/s/gfqf5jlzidn6q

File: inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/InferredSpansProcessorBuilder.java [hunk 7]
```diff
@@ -194,17 +195,23 @@ public InferredSpansProcessorBuilder startScheduledProfiling(boolean startSchedu
...
 
   /** For testing only. */
-  InferredSpansProcessorBuilder jfrFile(@Nullable File jfrFile) {
+  public InferredSpansProcessorBuilder jfrFile(@Nullable File jfrFile) {
     this.jfrFile = jfrFile;
     return this;
   }
 
+  /** For testing only. */
+  public InferredSpansProcessorBuilder tempDir(@Nullable File tempDir) {
```
Comment (SylvainJuge) [inline inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/InferredSpansProcessorBuilder.java:210]: [minor] not related to this PR, but we could probably replace usage of `File` with `Path` to prevent having to call `toFile`.

File: inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfiler.java [hunk 8]
```diff
@@ -739,18 +777,25 @@ public void start() {
...
+      profilerLock.unlock();
     }
   }
 
+  @SuppressWarnings({"FutureReturnValueIgnored", "Interruption"})
   public void stop() throws InterruptedException, IOException {
     // cancels/interrupts the profiling thread
+    if (profilingTask != null) {
+      profilingTask.cancel(true);
+    }
```
Comment (SylvainJuge) [inline inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfiler.java:798]: [minor] I would suggest to also wrap the access to `profilingTask` and potentially modifying its state with the `profilerLock`, at least for consistency with the other call to `.cancel(true)` above. There is however no side effect on potentially calling this twice as the return value of `cancel(...)` is ignored.

File: inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/asyncprofiler/JfrParser.java [hunk 9]
```diff
@@ -93,6 +93,9 @@ public void parse(
     this.includedClasses = includedClasses;
     bufferedFile.setFile(file);
     long fileSize = bufferedFile.size();
+    if (fileSize == 0) {
+      return;
+    }
```
Comment (SylvainJuge) [inline inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/asyncprofiler/JfrParser.java:98]: Is the case of empty file covered by any existing test ? I haven't seen any change related to this in the tests.

File: inferred-spans/src/test/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfilerTest.java [hunk 10]
```diff
@@ -44,6 +43,10 @@
 @DisabledOnOpenJ9
 class SamplingProfilerTest {
 
+  static {
+    ProfilingActivationListener.ensureInitialized();
```
Comment (SylvainJuge) [inline inferred-spans/src/test/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfilerTest.java:48]: what is the benefit of explicitly calling this in the tests and not in production code ? is there any benefit of doing this and if yes maybe a comment could be welcome.

File: inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfiler.java [hunk 11]
```diff
@@ -394,37 +404,62 @@ public void run() {
...
+          logger.fine("Profiler already started. Stopping and restarting.");
+          try {
+            profiler.stop();
+          } catch (RuntimeException ignore) {
+            logger.log(Level.FINE, "Ignored error on stopping profiler", ignore);
+          }
+          startMessage = profiler.execute(startCommand);
+        } else {
+          throw e;
+        }
```
Comment (SylvainJuge) [inline inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfiler.java:439]: Is is a known failure mode of async profiler here ? If so, then maybe having a dedicated method to wrap this "when exception is thrown stop, start and try again" logic could make it slightly more readeable.

File: inferred-spans/src/test/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfilerTest.java (hunk 10 above)
Comment (jackshirazi) [reply inferred-spans/src/test/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfilerTest.java:48]: the ProfilingActivationListener has a static initializer which has to be executed before any Context access. This happens in production, but is not guaranteed in test because we start things out of order to setup tests

File: inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfiler.java (hunk 11 above)
Comment (jackshirazi) [reply inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfiler.java:439]: this is testing fragility under concurrent test runs, I'd be surprised to see it get hit in production. Especially as dynamic updates to the test durations will be few and far in between in reality

File: inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/asyncprofiler/JfrParser.java (hunk 9 above)
Comment (jackshirazi) [reply inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/asyncprofiler/JfrParser.java:98]: good point, test added now

File: inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/InferredSpansProcessorBuilder.java (hunk 7 above)
Comment (jackshirazi) [reply inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/InferredSpansProcessorBuilder.java:210]: leaving this for another time

File: inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfiler.java (hunk 8 above)
Comment (jackshirazi) [reply inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/internal/SamplingProfiler.java:798]: leaving this for another time

**Review by SylvainJuge — APPROVED** [review]

File: inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/InferredSpansProcessorBuilder.java [hunk 12]
```diff
@@ -194,17 +195,23 @@ public InferredSpansProcessorBuilder startScheduledProfiling(boolean startSchedu
   }
 
   /** For testing only. */
-  InferredSpansProcessorBuilder activationEventsFile(@Nullable File activationEventsFile) {
+  public InferredSpansProcessorBuilder activationEventsFile(@Nullable File activationEventsFile) {
```
Comment (laurit) [inline inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/InferredSpansProcessorBuilder.java]: are you sure these need to be added to the public api?

Comment (jackshirazi) [reply inferred-spans/src/main/java/io/opentelemetry/contrib/inferredspans/InferredSpansProcessorBuilder.java]: good catch, thanks. They don't

**Review by laurit — APPROVED** [review]
